# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='permite_trabalhos',
            field=models.BooleanField(default=False, verbose_name='permitir submiss\xe3o de trabalhos'),
        ),
    ]
