# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('nome',),
                'verbose_name': '\xe1rea',
                'verbose_name_plural': '\xe1reas',
            },
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('arquivo', models.FileField(upload_to='trabalhos')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabalhos', to='trabalhos.AreaTema', verbose_name='\xe1rea')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabalhos', to='eventos.Inscricao')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabalhos', to='trabalhos.Modalidade')),
            ],
            options={
                'ordering': ('titulo',),
            },
        ),
    ]
