# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='observa\xe7\xf5es'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='situacao',
            field=models.IntegerField(choices=[(0, b'Pendente'), (1, b'Aprovado'), (2, 'Aprovado com corre\xe7\xf5es'), (3, b'Reprovado')], default=0, verbose_name='situação'),
        ),
    ]
